# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-12 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost-reservation', '0003_auto_20170508_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='url',
        ),
        migrations.AlterField(
            model_name='resource',
            name='end_time',
            field=models.TimeField(verbose_name='available until'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='start_time',
            field=models.TimeField(verbose_name='available from'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
