# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-13 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ost-reservation', '0004_auto_20170512_2152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservations',
            new_name='Reservation',
        ),
    ]
