# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-13 16:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ost-reservation', '0005_auto_20170513_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 13, 16, 28, 6, 306678, tzinfo=utc), verbose_name='res date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(verbose_name='res end'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(verbose_name='res start'),
        ),
    ]
