# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-13 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost-reservation', '0007_resource_last_res_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='resource',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='resource',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='resource',
            name='reserve_count',
            field=models.IntegerField(default=0),
        ),
    ]
